export const CAR_MAKES = [
  "Toyota",
  "Lexus",
  "BMW",
  "Mercedes-Benz",
  "Audi",
  "Volkswagen",
  "Ford",
  "Chevrolet",
  "Nissan",
  "Honda",
  "Mazda",
  "Hyundai",
  "Kia",
  "Subaru",
  "Mitsubishi",
  "Isuzu",
  "Jeep",
  "Land Rover",
  "Porsche",
  "Volvo",
  "Other",
] as const;

export const POPULAR_MODELS: Record<string, string[]> = {
  Toyota: ["Hilux", "Fortuner", "Corolla", "RAV4", "Land Cruiser", "Camry", "Yaris", "Prado", "Quantum", "Avanza"],
  Lexus: ["IS", "ES", "GS", "LS", "RX", "NX", "LX", "RC", "LC"],
  BMW: ["3 Series", "5 Series", "7 Series", "X3", "X5", "X1", "1 Series", "4 Series", "X7", "M3", "M5"],
  "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "A-Class", "CLA", "G-Class", "AMG GT"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8", "A5", "TT", "RS"],
  Volkswagen: ["Polo", "Golf", "Tiguan", "Amarok", "Passat", "Jetta", "T-Roc", "Touareg", "Caddy"],
  Ford: ["Ranger", "Everest", "Fiesta", "Focus", "EcoSport", "Mustang", "Kuga", "Figo"],
  Chevrolet: ["Spark", "Aveo", "Cruze", "Captiva", "Trailblazer", "Silverado"],
  Nissan: ["NP200", "NP300", "Navara", "X-Trail", "Qashqai", "Micra", "Almera", "Patrol"],
  Honda: ["Civic", "Accord", "CR-V", "HR-V", "Jazz", "Ballade"],
  Mazda: ["2", "3", "CX-3", "CX-5", "CX-30", "6", "BT-50"],
  Hyundai: ["i10", "i20", "Accent", "Elantra", "Tucson", "Santa Fe", "Creta", "Venue"],
  Kia: ["Picanto", "Rio", "Cerato", "Sportage", "Sorento", "Seltos", "Stinger"],
  Subaru: ["Impreza", "WRX", "Forester", "Outback", "XV", "Legacy"],
  Mitsubishi: ["Triton", "Pajero Sport", "ASX", "Eclipse Cross", "Outlander"],
  Isuzu: ["D-Max", "MU-X", "KB"],
  Jeep: ["Wrangler", "Cherokee", "Grand Cherokee", "Compass", "Renegade"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Sport", "Evoque"],
  Porsche: ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718"],
  Volvo: ["XC40", "XC60", "XC90", "S60", "S90", "V60"],
  Other: ["Custom"],
};

export type CarMake = typeof CAR_MAKES[number];
